### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by SPPIDER** [ravizhan/yangcong-dl#1]
如果能修复的话，大佬修一下吧
另外下载器需要ffmpeg，静默运行没有提示

**Comment by ravizhan** [comment]
- 经过排查，洋葱学院的接口进行了加密处理，已完成分析
  大概明天会更新
- 下载器的问题也会在明天的更新中解决

**Comment by ravizhan** [comment]
@SPPIDER 已修复，请下载v0.4版本使用
