### ISSUE TITLE
一些Bug&建议

### ISSUE THREAD

**Issue by GDWGH** [ravizhan/yangcong-dl#2]
bug：
①：当ISP是Cloudflare时（[172.69.99.63] 来自：中国香港 Cloudflare） 软件会闪退 
②：当提示已完成的时候 还是会产生 数字.ts 文件

建议:
①：添加字幕功能 （我在用IDM抓取的时候 是会出现字幕的）
②：文件夹改名成 版本/年级上册/下册 /单元     （太麻烦 按照序号找）

**Comment by ravizhan** [comment]
抱歉，由于洋葱学院网站已更新并修复了该项目所用的权限漏洞，且该项目仅作为技术验证，不适合正式使用。
综上，该项目将停止维护。
