### ISSUE TITLE
视频的标题和内容对不上号，而且并不能爬取全部的视频。

### ISSUE THREAD

**Issue by Catc326** [ravizhan/yangcong-dl#4]
![微信图片_20240208123352](https://github.com/ravizhan/yangcong-dl/assets/123161959/c3f5ca38-7c38-447f-82d2-4358abfd0303)
选修一 共有63个视频这里却只有55个
![微信图片_20240208123401](https://github.com/ravizhan/yangcong-dl/assets/123161959/8032327b-127c-4fef-a3a0-deb0896b2e47)
我再次选择第4单元又冒出来了开始没有爬到的视频，但这时的视频仍然少了一个，并不是最后一个视频而是中间的一个。
还有命名不对比如第四单元的最后一个视频是金属的腐蚀却被命名成了电解池中的计算

**Comment by ravizhan** [comment]
已修复 https://github.com/ravizhan/yangcong-dl/commit/c19dc705a7cfd98b5f68327492071012e9f1a3f5
