### ISSUE TITLE
视频下载有问题

### ISSUE THREAD

**Issue by Catc326** [ravizhan/yangcong-dl#5]
这里先祝开发者新年快乐
下面是问题：
![1](https://github.com/ravizhan/yangcong-dl/assets/123161959/fe7db26a-8ffa-40ff-aebe-26e651987b25)
再选择下载全部内容时不能下载成功
Traceback (most recent call last):
  File "c:\Users\Catc\Downloads\yangcong-dl-0.7\main.py", line 158, in <module>
    download.download(m3u8_urls, video_names, download_dir)
  File "c:\Users\Catc\Downloads\yangcong-dl-0.7\download.py", line 33, in download
    urls[i] = urls[i].replace('\n', '')
              ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
但是当我选择单独的视频时却可以下载
![2](https://github.com/ravizhan/yangcong-dl/assets/123161959/0304aefe-6a63-4561-ad49-6fdf8e3656d9)
还有些建议能不能直接选择某个学科某个版本后直接下载完，就是初中或者高中这一学科的内容都下载完（主要怕哪天就被修复了，代表穷学生谢谢你）

**Comment by Catc326** [comment]
我又实测了一下是完全下载不了

**Comment by Simpchao** [comment]
为啥显示下载成功了，但找不到下载的视频文件
![{D4E5CAD3-9A3C-4359-B7FA-28FF587888B1}](https://github.com/ravizhan/yangcong-dl/assets/153895854/d52e2487-81ed-4466-9855-e8e326ae288d)
这个文件地址找不到
