### ISSUE TITLE
topic["video"]["addresses"]是空的

### ISSUE THREAD

**Issue by My-Carolyn** [ravizhan/yangcong-dl#8]
![无标题](https://github.com/ravizhan/yangcong-dl/assets/34833506/1acd22bd-c1dc-4428-b72b-ab71d7af984f)

**Comment by My-Carolyn** [comment]
下载不了视频，望作者修复

**Comment by ravizhan** [comment]
已经注意到了该问题，上周回去看了下，得换接口了。比较恶心的一点是，现在的m3u8文件里的视频密钥加了鉴权，需要逆向一下算法。
类似这种
https://school-api.yangcong345.com/videoBase/getHlsEncryptKey?id=ad35221a-9e41-482b-bea1-cc846c925bc9&x-key=dj0yJnNNZXRob2Q9bWQ1JnZJZD0zNWI5N2Y3Yy03ZjQzLTExZWMtYmQzNi01Mzk2NThjMGViMDMmdGltZXN0YW1wPTE3MTIyMTM2MTQzMDgmc2lnbmF0dXJlPTg0MGJmZTc4NTdiZjUyMGE0YmY0OTQ0NDViNzU4NDU3
但是奈何本人高三了，逆向技术也不佳，估计得等到五一或者高考后了

**Comment by ravizhan** [comment]
当然也期待有大佬来pr (*^o^*)

**Comment by ravizhan** [comment]
逆向成功了，预计五一更新

**Comment by yyds070422** [comment]
加油兄弟  很想要这些

**Comment by My-Carolyn** [comment]
@ravizhan 能给个思路吗？，是找到getHlsEncryptKey后面的x-key的生成规律，还是找到直接生成m3u8的key的生成方法？

**Comment by ravizhan** [comment]
x-key
m3u8里面的密钥是没x-key的
________________________________
发件人: mbn ***@***.***>
发送时间: 2024年4月15日 11:06
收件人: ravizhan/yangcong-dl ***@***.***>
抄送: ravizhan ***@***.***>; Mention ***@***.***>
主题: Re: [ravizhan/yangcong-dl] topic["video"]["addresses"]是空的 (Issue #8)


@ravizhan<https://github.com/ravizhan> 能给个思路吗？，是找到getHlsEncryptKey后面的x-key的生成规律，还是找到直接生成m3u8的key的生成方法？

―

**Comment by My-Carolyn** [comment]
m3u8的链接怎么获取的？，我现在也把m3u8的加密密钥逆向出来了（也不算逆向，直接从他们网站把那段生成x-key的代码复制下来运行就可以），

**Comment by yyds070422** [comment]
加油孩子  马上月考了  想看洋葱 @ravizhan

**Comment by bnaand** [comment]
> 加油孩子 马上月考了 想看洋葱 @ravizhan

其实不闲麻烦，可以下载m3u8文件+key文件，修改m3u8里的地址，把key和m3u8一起拖拽进m3u8dl，可以下载。就是比较麻烦，不如up主批量下载来的方便。

**Comment by yyds070422** [comment]
> > 加油孩子 马上月考了 想看洋葱 @ravizhan
> 
> 其实不闲麻烦，可以下载m3u8文件+key文件，修改m3u8里的地址，把key和m3u8一起拖拽进m3u8dl，可以下载。就是比较麻烦，不如up主批量下载来的方便。

咋搞呢  求教

**Comment by yyds070422** [comment]
> > 加油孩子 马上月考了 想看洋葱 @ravizhan
> 
> 其实不闲麻烦，可以下载m3u8文件+key文件，修改m3u8里的地址，把key和m3u8一起拖拽进m3u8dl，可以下载。就是比较麻烦，不如up主批量下载来的方便。

能否给个视频教程  孩子是小白

**Comment by bnaand** [comment]
这个方法只适合能看到的视频下载。
先用浏览器下载m3u8文件
在用原码找key下载key文件
修改m3u8文件里的内容如下 ，修改好拖进m3u8dl就可以下载了
![3](https://github.com/ravizhan/yangcong-dl/assets/106130584/f2c76878-4d8f-43e3-8857-4edd6888d9bd)
![2](https://github.com/ravizhan/yangcong-dl/assets/106130584/99ab6d4f-6cc8-4460-b7d1-2f3cf6224edf)
